<?php

/**
 * BaseResult
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $path
 * @property bigint $job_id
 * @property Job $Job
 * 
 * @method string getPath()   Returns the current record's "path" value
 * @method bigint getJobId()  Returns the current record's "job_id" value
 * @method Job    getJob()    Returns the current record's "Job" value
 * @method Result setPath()   Sets the current record's "path" value
 * @method Result setJobId()  Sets the current record's "job_id" value
 * @method Result setJob()    Sets the current record's "Job" value
 * 
 * @package    Protorama Blue
 * @subpackage model
 * @author     Tino Truppel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResult extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('result');
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('job_id', 'bigint', 20, array(
             'type' => 'bigint',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Job', array(
             'local' => 'job_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}