<?php

/**
 * BaseImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property string $params
 * @property string $hash
 * @property string $path
 * @property timestamp $accessed_at
 * @property timestamp $processed_at
 * 
 * @method string    getUrl()          Returns the current record's "url" value
 * @method string    getParams()       Returns the current record's "params" value
 * @method string    getHash()         Returns the current record's "hash" value
 * @method string    getPath()         Returns the current record's "path" value
 * @method timestamp getAccessedAt()   Returns the current record's "accessed_at" value
 * @method timestamp getProcessedAt()  Returns the current record's "processed_at" value
 * @method Image     setUrl()          Sets the current record's "url" value
 * @method Image     setParams()       Sets the current record's "params" value
 * @method Image     setHash()         Sets the current record's "hash" value
 * @method Image     setPath()         Sets the current record's "path" value
 * @method Image     setAccessedAt()   Sets the current record's "accessed_at" value
 * @method Image     setProcessedAt()  Sets the current record's "processed_at" value
 * 
 * @package    webtopng
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => '255',
             ));
        $this->hasColumn('params', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('hash', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'notblank' => true,
             'length' => '255',
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => '255',
             ));
        $this->hasColumn('accessed_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('processed_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}