<?php

/**
 * BaseRenderJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $params
 * @property string $hash
 * @property string $path
 * @property enum $status
 * @property text $error_message
 * @property timestamp $accessed_at
 * @property timestamp $process_started_at
 * @property timestamp $process_finished_at
 * @property string $type
 * 
 * @method text      getParams()              Returns the current record's "params" value
 * @method string    getHash()                Returns the current record's "hash" value
 * @method string    getPath()                Returns the current record's "path" value
 * @method enum      getStatus()              Returns the current record's "status" value
 * @method text      getErrorMessage()        Returns the current record's "error_message" value
 * @method timestamp getAccessedAt()          Returns the current record's "accessed_at" value
 * @method timestamp getProcessStartedAt()    Returns the current record's "process_started_at" value
 * @method timestamp getProcessFinishedAt()   Returns the current record's "process_finished_at" value
 * @method string    getType()                Returns the current record's "type" value
 * @method RenderJob setParams()              Sets the current record's "params" value
 * @method RenderJob setHash()                Sets the current record's "hash" value
 * @method RenderJob setPath()                Sets the current record's "path" value
 * @method RenderJob setStatus()              Sets the current record's "status" value
 * @method RenderJob setErrorMessage()        Sets the current record's "error_message" value
 * @method RenderJob setAccessedAt()          Sets the current record's "accessed_at" value
 * @method RenderJob setProcessStartedAt()    Sets the current record's "process_started_at" value
 * @method RenderJob setProcessFinishedAt()   Sets the current record's "process_finished_at" value
 * @method RenderJob setType()                Sets the current record's "type" value
 * 
 * @package    Protorama Blue
 * @subpackage model
 * @author     Tino Truppel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRenderJob extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('render_job');
        $this->hasColumn('params', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('hash', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'queued',
              1 => 'processing',
              2 => 'processed',
              3 => 'failed',
             ),
             'notnull' => true,
             'notblank' => true,
             ));
        $this->hasColumn('error_message', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('accessed_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('process_started_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('process_finished_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->setSubClasses(array(
             'ImageRenderJob' => 
             array(
              'type' => 'image',
             ),
             'PdfRenderJob' => 
             array(
              'type' => 'pdf',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}