<?php

/**
 * BaseImageRenderJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    Protorama Blue
 * @subpackage model
 * @author     Tino Truppel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImageRenderJob extends RenderJob
{
    public function setUp()
    {
        parent::setUp();
        
    }
}