<?php

/**
 * ImageRenderJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageRenderJobTable extends RenderJobTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageRenderJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageRenderJob');
    }
}