<?php

/**
 * ImageRenderJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Protorama Blue
 * @subpackage model
 * @author     Tino Truppel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ImageRenderJob extends BaseImageRenderJob
{
	public function getCommand() {		
		$command = "";
		//if($options['env'] == 'prod')	$command .= 'timeout 30 '; // timeout
		$command .= getcwd().'/tools/wkhtmltoimage-amd64 ';  // wkhtmltoimage binary amd64
		$command .= '--zoom '.round($this->getParam('width')/1024, 2).' --width '.$this->getParam('width').' ';
		$command .= '--format '.$this->getParam('format').' ';
		$command .= '"'.$this->getUrl().'" '; // url
		//$command .= '--custom-header "If-Modified-Since" "'.$modified.'" ';
		$command .= getcwd().'/web/uploads/'.$this->getHash().'.'.$this->getParam('format').'; '; // image path
		return $command;
	}
}
