<?php

/**
 * ImageJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageJobTable extends JobTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageRenderJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageJob');
    }
}