<?php

/**
 * Job
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Protorama Blue
 * @subpackage model
 * @author     Tino Truppel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Job extends BaseJob
{

	protected function doRender() {
		throw new Exception('Method "doRender" only implemented in child classes.');
	}

	public function validateParams() {
		return true;
	}

	public function render() {
		if ($this->validateParams()) {
			// render
			try {
				$this->setProcessStartedAt(date('Y-m-d H:i:s'));
				$this->setStatus('processing');
				$this->save();
				$this->doRender();
				if ($this->getStatus() == 'processed') {
					// check result
					clearstatcache();
					if(file_exists(getcwd().'/web/'.$this->getSavePath())) {
						$this->setProcessFinishedAt(date('Y-m-d H:i:s'));
						
						// save new result
						$result = new Result();
						$result->setPath($this->getSavePath());
						$this->getResults()->add($result);							
					} else {
						$this->setStatus('failed');
						$this->setErrorMessage('Unkown error occured: could not find rendered file');
					}
				}
			} catch (Exception $e) {
				$this->setStatus('failed');
				$this->setErrorMessage($e->getMessage());
			}
		}
		return $this->save();
	}

	public function getSavePath() {
		return 'uploads/'.$this->getHash().'-'.strtotime($this->getProcessStartedAt()).'.'.$this->getParam('format');
	}

	public function getParam($name) {
		$params = json_decode($this->getParams(), true);
		return $params[$name];
	}

	public function getLastResult() {
		return $this->getResults()->getFirst();
	}
}
