<?php

/**
 * PdfJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PdfJobTable extends JobTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PdfJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PdfJob');
    }
}