<?php

/**
 * PdfRenderJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PdfRenderJobTable extends RenderJobTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PdfRenderJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PdfRenderJob');
    }
}