<?php

/**
 * PdfRenderJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Protorama Blue
 * @subpackage model
 * @author     Tino Truppel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PdfRenderJob extends BasePdfRenderJob
{
	public function getCommand() {		
		$command = "";
		//if($options['env'] == 'prod')	$command .= 'timeout 30 '; // timeout
		$command .= getcwd().'/tools/wkhtmltopdf-amd64 ';  // wkhtmltopdf binary amd64
		$command .= '"'.$this->getParam('url').'" '; // url
		//$command .= '--custom-header "If-Modified-Since" "'.$modified.'" ';
		$command .= getcwd().'/web/uploads/'.$this->getHash().'.'.$this->getParam('format').'; '; // pdf path
		return $command;
	}
}