<?php

/**
 * RenderJob
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Protorama Blue
 * @subpackage model
 * @author     Tino Truppel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RenderJob extends BaseRenderJob
{
	public function getCommand() {
		throw new Exception('Method "getCommand" only implemented in child classes.');
	}

	public function validateParams() {
		return true;
	}

	public function render() {
		if ($this->validateParams()) {
			// render
			try {
				$this->setProcessStartedAt(date('Y-m-d H:i:s'));
				$this->setStatus('processing');
				$this->save();
				shell_exec($this->getCommand());
				$this->setProcessFinishedAt(date('Y-m-d H:i:s'));
				$this->setStatus('processed');
			} catch (Exception $e) {
				$this->setStatus('failed');
				$this->setErrorMessage($e->getMessage());
			}

			// check result
			clearstatcache();
			if(file_exists(getcwd().'/web/uploads/'.$this->getHash().'.'.$this->getParam('format'))) {
				$this->setPath('uploads/'.$this->getHash().'.'.$this->getParam('format'));
			} else {
				$this->setPath('images/could-not-render.png');
				$this->setStatus('failed');
				$this->setErrorMessage('Unkown error occurs');
			}
		}
		return $this;
	}

	public function getParam($name) {
		$params = json_decode($this->getParams(), true);
		return $params[$name];
	}

	public function getResult() {
		if ($this->getStatus() == 'failed') {
			$this->setPath('images/could-not-render.png');
		}
		// in the case this method is called within an action
		sfContext::getInstance()->getConfiguration()->loadHelpers(array('Asset'));
		return image_path('/'.$this->getPath(), true);
	}
}
