<?php

/**
 * RenderJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RenderJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RenderJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RenderJob');
    }
    
	public function getNextJob() {
		return  $this->createQuery('j')
			 	->where('j.process_finished_at IS NULL OR j.accessed_at > j.process_finished_at')
		    	->limit(1)
		    	->orderBy('j.accessed_at DESC')
		    	->execute()
		    	->getFirst();
	}
}