<?php

/**
 * ResultTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResultTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResultTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Result');
    }
}