<?php

/**
 * WordJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WordJobTable extends JobTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WordJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WordJob');
    }
}