<?php

require_once sfConfig::get('sf_lib_dir').'/vendor/PHPWord/PHPWord.php';

/**
 * WordRenderJob
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Protorama Blue
 * @subpackage model
 * @author     Tino Truppel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WordRenderJob extends BaseWordRenderJob
{

	public function render() {
		$this->setProcessStartedAt(date('Y-m-d H:i:s'));
		$this->setStatus('processing');
		$this->save();
		$continue = true;
		foreach ($this->getParam('pages') as $page) {
			$subJob = RenderJobTable::getInstance()->createNewJob($page);
			if ($subJob->getStatus() == 'failed') {
				$this->setStatus('failed')->setErrorMessage('Sub job failed with: "'.$subJob->getErrorMessage().'"');
				return $this;
			} else if ($subJob->getStatus() != 'processed') {
				$continue = false;
			}
		}

		if ($continue) {
			$PHPWord = new PHPWord();
			foreach ($this->getParam('pages') as $page) {
				$subJob = RenderJobTable::getInstance()->createNewJob($page);
				$section = $PHPWord->createSection();
				$section->addText($page['title']);
				$section->addTextBreak(2);
				$section->addImage(getcwd().'/web/uploads/'.$subJob->getHash().'.'.$subJob->getParam('format'));
				$section->addText($page['caption']);
			}
			$objWriter = PHPWord_IOFactory::createWriter($PHPWord, 'Word2007');
			$objWriter->save(getcwd().'/web/uploads/'.$this->getHash().'.'.$this->getParam('format'));
			$this->setStatus('processed');				
			$this->setProcessFinishedAt(date('Y-m-d H:i:s'));
			$this->setPath('uploads/'.$this->getHash().'.'.$this->getParam('format'));
		} else {
			$this->setStatus('waiting');
		}
		return $this;
	}

	public function validateParams() {
		$params = json_decode($this->getParams(), true);
		if (!isset($params['url'])) {
			$this->setStatus('failed');
			$this->setErrorMessage('The parameter URL is required');
			return false;
		}
		if (!filter_var($params['url'], FILTER_VALIDATE_URL) && !filter_var('http://'.$params['url'], FILTER_VALIDATE_URL) && !filter_var('https://'.$params['url'], FILTER_VALIDATE_URL)) {
			$this->setStatus('failed');
			$this->setErrorMessage('The value of the parameter URL is not valid');
			return false;
		}
		return true;
	}
}
