dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=pr_blue_dev'
      username: pr_blue_dev
      password: pr_blue_dev
      
prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=pr_blue'
      username: pr_blue
      password: fPYyUyYnVvrVR4LQ