dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=protorama_blue'
      username: protorama_blue
      password: protorama_blue
      
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=protorama_blue'
      username: protorama_blue
      password: fPYyUyYnVvrVR4LQ