<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/02 01:35:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=webtopng',
  'username' => 'pidoco',
  'password' => 'pidoco',
  'name' => 'doctrine',
)),);
