<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/05/02 15:01:38
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfwidgetformdoctrinechoice' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrineconnectionprofiler' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineconnectionlistener' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineformfiltergenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrinecolumn' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfvalidatordoctrinechoice' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfdoctrinedqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinebuildfilterstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinebuildsqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrineinsertsqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinemigratetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinedatadumptask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinebuildtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinebasetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuildformstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinecreatemodeltables' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedataloadtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinebuilddbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinedropdbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebuildmodeltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegenerateadmintask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildschematask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrineroute' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfformfilterdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfformdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfwebdebugpaneldoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'swift_doctrinespool' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinerecord' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sftesterdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinepager' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinecli' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',

  // project
  'rendertask' => '/home/tino/workspace/WebToPng/lib/task/renderTask.class.php',
  'baseform' => '/home/tino/workspace/WebToPng/lib/form/BaseForm.class.php',
  'baseimageform' => '/home/tino/workspace/WebToPng/lib/form/doctrine/base/BaseImageForm.class.php',
  'baseformdoctrine' => '/home/tino/workspace/WebToPng/lib/form/doctrine/BaseFormDoctrine.class.php',
  'imageform' => '/home/tino/workspace/WebToPng/lib/form/doctrine/ImageForm.class.php',
  'baseimageformfilter' => '/home/tino/workspace/WebToPng/lib/filter/doctrine/base/BaseImageFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/tino/workspace/WebToPng/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'imageformfilter' => '/home/tino/workspace/WebToPng/lib/filter/doctrine/ImageFormFilter.class.php',

  // project_model
  'baseimage' => '/home/tino/workspace/WebToPng/lib/model/doctrine/base/BaseImage.class.php',
  'image' => '/home/tino/workspace/WebToPng/lib/model/doctrine/Image.class.php',
  'imagetable' => '/home/tino/workspace/WebToPng/lib/model/doctrine/ImageTable.class.php',

  // application
  'myuser' => '/home/tino/workspace/WebToPng/apps/frontend/lib/myUser.class.php',
  'abstractrenderer' => '/home/tino/workspace/WebToPng/apps/frontend/lib/URLRender/abstractRenderer.class.php',
  'pdfrenderer' => '/home/tino/workspace/WebToPng/apps/frontend/lib/URLRender/pdfRenderer.class.php',
  'pngrenderer' => '/home/tino/workspace/WebToPng/apps/frontend/lib/URLRender/pngRenderer.class.php',
  'rendererfactory' => '/home/tino/workspace/WebToPng/apps/frontend/lib/URLRender/rendererFactory.class.php',

  // modules
);
