RenderJob:
  actAs: { Timestampable: ~ }
  columns:        
    params: { type: text }
    hash: { type: string(255), notnull: true, unique: true, notblank: true }
    path: { type: string(255), notnull: true, notblank: true }
    status: { type: enum, values: ['new', 'queued', 'processing', 'processed', 'failed', 'waiting'], notnull: true, notblank: true }
    error_message: { type: text }
    accessed_at: { type: timestamp, notnull: true }
    process_started_at: { type: timestamp, notnull: false }
    process_finished_at: { type: timestamp, notnull: false }
    
ImageRenderJob:
  inheritance:
    extends: RenderJob
    type: column_aggregation
    keyField: type
    keyValue: image
    
PdfRenderJob:
  inheritance:
    extends: RenderJob
    type: column_aggregation
    keyField: type
    keyValue: pdf
    
WordRenderJob:
  inheritance:
    extends: RenderJob
    type: column_aggregation
    keyField: type
    keyValue: word